import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}:
  Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html className="dark">
    <head>
      <title>Create Next App</title>
      <link rel="icon" href="./favicon.ico"/>
    </head>
    <body className={inter.className}>
    <header className="flex justify-center items-center relative w-full">
      <Navbar/>
    </header>
    {children}
    </body>
    </html>
  );
}
